baseURL: https://test.delic.rs
languageCode: en-us
buildDrafts: false
canonifyURLs: true
contentDir: content
layoutsDis: layouts
publishDir: public

author: Bojan Delić
title: bits and bytes

theme: hugo-goa
disqusShortname: 'del-boy'
enableRobotsTXT: true
metaDataFormat: yaml
copyright: Copyright (c) 2008 - 2017, Bojan Delic; all rights reserved

permalinks:
  blog: /:section/:year/:filename/

taxonomies:
  tag: tags
  category: categories
params:
  author: Bojan Delić
  intro: "\"First, solve the problem. Then, write the code\" - John Johnson"
  description: Software engineer from Belgrade, Serbia. Writing code at [SevenBridges](https://sevenbridges.com)
  authorimage: avatar.jpg
  dateformat: Jan 2, 2006
  summary: true
  meta:
    description: Personal blog about my adventures in the world of software development
    keywords: development,personal,golang,go,python
  social:
    github: delicb
    instagram: delicb
    linkenin: bojandelic
    twitter: dercibald
    facebook: bojan.delic
    stackoverflow: 61363
    email: contact@delic.in.rs
  extra: 
    copyright: "@ 2017. Bojan Delić. [Some Rights Reserved](https://creativecommons.org/licenses/by/4.0/)"
    poweredby: true
    highlightjs:
      enabled: true
      add_langages:
        - go
      theme: tomorrow

menu:
  main:
    - name: projects
      weight: 50
      identifier: projects
      url: /project/
    - name: blog
      weight: 100
      identifier: post
      url: /blog/
    - name: quotes
      weight: 200
      identifier: quotes
      url: /quote/
    - name: about
      weight: 300
      identifier: about
      url: /about/
